#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标(经纬度+精度+海拔) (Shadowrocket 小火箭) | 选点页面: 请使用自建 wloc-locator Worker
#!author=Yu9191 Rewrite
#!homepage=https://github.com/admin0330/wloc-locator
#!icon=https://cdn.jsdelivr.net/gh/admin0330/wloc-locator@main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://cdn.jsdelivr.net/gh/admin0330/wloc-locator@main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&altitude=15&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://cdn.jsdelivr.net/gh/admin0330/wloc-locator@main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
